# Hough lines

In [5]:
import matplotlib.pyplot as plt
import imutils

In [6]:
def main():
    
    import cv2
    import numpy as np
    from scipy.spatial import distance as dist
    
    
  
    cap = cv2.VideoCapture('C:/Users/shrin/Documents/Abhilash/tata steel/data in tata -new light/0 - 2020-02-26 15-40-18-083.mov')
    #cap = cv2.VideoCapture('rtsp://admin:TATA_tsk123@10.152.235.180')

    cap.set(cv2.CAP_PROP_POS_FRAMES,200 + 300)
    alar = [420,1200 - 100  ,2041,1200 - 100  ]
    #alar = [420,1000   ,2041,1200 -40   ]

    leftEdge = 1200 +5 - 300 - 20 - 8
    
    dB = dist.euclidean(alar[:2],alar[-2:])
    pixelsPerMetric = dB / 1690
    
    
    def line_intersection(line1, line2):

        xdiff = (line1[0][0] - line1[1][0], line2[0][0] - line2[1][0])
        ydiff = (line1[0][1] - line1[1][1], line2[0][1] - line2[1][1])
        
        def det(a, b):
            return a[0] * b[1] - a[1] * b[0]

        div = det(xdiff, ydiff)
        if div == 0:
            raise Exception('lines do not intersect')

        d = (det(*line1), det(*line2))
        x = det(d, xdiff) / div
        y = det(d, ydiff) / div
        return x, y

    '''def edgeCalLeft(leftSide):
        box = 15
        if (sum(thresh[val,leftSide+1:leftSide + 1 + box])/(box*255))  != 0.0:
                print("not",sum(thresh[val,leftSide+1: leftSide + 1 + box])/(box*255))
                print("------",np.nonzero(thresh[val, leftSide+box+1:-1])[0][0])
                leftSide_ = np.nonzero(thresh[val, leftSide+box+1:-1])[0][0] #+ leftSide
                print("after-->",leftSide_,"\n")
                edgeCalLeft(leftSide_)
                return leftSide
                
        else:
            return leftSide'''
    
    while(True):
        ret, img = cap.read()
        img = imutils.rotate(img,.54)
        gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

        '''laplacian = cv2.Laplacian(gray,cv2.CV_64F)
        sobelx = cv2.Sobel(gray,cv2.CV_64F,1,0,ksize=5)
        sobely = cv2.Sobel(gray,cv2.CV_64F,0,1,ksize=5)'''

        #img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        b,g,r = cv2.split(img.copy()) 
        
        yuv = cv2.cvtColor(img.copy(),cv2.COLOR_BGR2YUV)
        y,u,vb = cv2.split(yuv)

        randv = cv2.addWeighted(y, .5, b, 2., 0.0)  #good 220
        #randv = cv2.addWeighted(y, .5, r, 2.1, 0.0)

        
        dst = cv2.addWeighted(y, 0.005, randv, 1.3, 0.0)
        
        blur = cv2.GaussianBlur(dst,(3,3),0)

        _,thresh = cv2.threshold(blur,220,255,cv2.THRESH_BINARY )
        
        
        
        val = alar[1]
        #thresh = cv2.erode(thresh,(255,255),iterations = 4 )
        thresh[:,2170:] = 0
        thresh[:,0:199] = 0
        thresh[0:val - 250,:] = 0
        thresh[val + 130:-1,:] = 0
        canny = cv2.Canny(thresh,200,255)
        laplacian = cv2.Laplacian(thresh,cv2.CV_64F)
        sobelx = cv2.Sobel(thresh,cv2.CV_64F,1,0,ksize=5)
        sobely = cv2.Sobel(thresh,cv2.CV_64F,0,1,ksize=5)
        
        

        #vertical = thresh
        # find the contours from the thresholded image
        _,contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        if np.count_nonzero(thresh[val,]) >= 500:
            #leftSide = np.nonzero(thresh[leftEdge,])[0][0]  - 39
            
            lines = cv2.HoughLinesP(canny,1,np.pi/180,100,minLineLength=400,maxLineGap=100) # minLineLength=100,maxLineGap=100
        #print(lines)
            leftSide = np.nonzero(thresh[val,])[0][0]
            for line in lines:
                x1,y1,x2,y2 = line[0]
                if abs(y2 - y1) > 50 :
                    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
                    print("x1->",x1,'y1',"\t","x2->",x2,'y2',y2)
                    print ("inter",line_intersection(((200,1100), (1280,val)), ((x1,y1),(x2,y2))))
                    
                    interX,interY = line_intersection(((200,1100), (1280,val)), ((x1,y1),(x2,y2)))
                    img = cv2.circle(img,(int(interX),int(interY)), 1, 0, 25)

            
                    leftSide = int(interX)
            
            
            
            print("before-->",leftSide)
            """_____________________________________________left-Logic___________________________________________________"""
            #leftSide = edgeCalLeft(leftSide)
            
            rightSide = np.nonzero(thresh[val,])[0][-1] 
            
            
            mmPpix = ((1/pixelsPerMetric)* (rightSide - leftSide)) 
            
            if mmPpix > 50:
                img  = cv2.line(img ,(leftSide ,alar[1]),(rightSide ,alar[3]),(255),4)


                img = cv2.circle(img,(leftSide,alar[1]) , 1, 0, 5)
                img = cv2.circle(img,(rightSide,alar[3]) , 1, 0, 5)

                font = cv2.FONT_HERSHEY_SIMPLEX
                img = cv2.putText(img,"{} mm".format(mmPpix),(0,330), font, 2 , (200,255,155), 2 , cv2.LINE_AA)

            
            
            '''verticalStructure = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 1520//50))
            # Apply morphology operations
            vertical = cv2.erode(thresh, verticalStructure)
            vertical = cv2.dilate(thresh, verticalStructure)
'''

        img1 = cv2.resize(img ,(int(1920/2),int(1080/2)))
        thresh1 = cv2.resize(thresh,(int(1920/2),int(1080/2)))
        canny1 = cv2.resize(canny,(int(1920/2),int(1080/2)))
        
        laplacian1 = cv2.resize(laplacian ,(int(1920/2),int(1080/2)))
        sobelx1 = cv2.resize(sobelx,(int(1920/2),int(1080/2)))
        sobely1 = cv2.resize(sobely,(int(1920/2),int(1080/2)))
        #cv2.cvtColor(img.copy(),cv2.COLOR_RGB2BGR)
        
        cv2.imshow('img ',img1)
        cv2.imshow(' thrsh ',thresh1)
        cv2.imshow('verticle',canny1)
        
        cv2.imshow('laplacian',laplacian1)
        cv2.imshow('sobelx',sobelx1)
        cv2.imshow('sobely',sobely1)


       


        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    
    cap.release()
    cv2.destroyAllWindows()

      
if __name__== "__main__":
    main()

before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before--> 199
before

# normal

In [8]:
def main():
    
    import cv2
    import numpy as np
    from scipy.spatial import distance as dist
    
  
    cap = cv2.VideoCapture('C:/Users/shrin/Documents/Abhilash/tata steel/data in tata -new light/0 - 2020-02-26 15-40-18-083.mov')
    #cap = cv2.VideoCapture('rtsp://admin:TATA_tsk123@10.152.235.180')

    cap.set(cv2.CAP_PROP_POS_FRAMES,200+300+50)
    alar = [420,1200 - 100  ,2041,1200 - 100  ]
    #alar = [420,1000   ,2041,1200 -40   ]

    leftEdge = 1200 +5 - 300 - 20 - 8
    
    dB = dist.euclidean(alar[:2],alar[-2:])
    pixelsPerMetric = dB / 1690
    
    
    
    while(True):
        ret, img = cap.read()

        #img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        b,g,r = cv2.split(img.copy()) 
        
        yuv = cv2.cvtColor(img.copy(),cv2.COLOR_BGR2YUV)
        y,u,vb = cv2.split(yuv)

        randv = cv2.addWeighted(y, .5, b, 2., 0.0)  #good 220
        #randv = cv2.addWeighted(y, .5, r, 2.1, 0.0)

        
        dst = cv2.addWeighted(y, 0.005, randv, 1.3, 0.0)
        
        blur = cv2.GaussianBlur(dst,(3,3),0)

        _,thresh = cv2.threshold(blur,220,255,cv2.THRESH_BINARY )
        
        
        
        val = alar[1]
        #thresh = cv2.erode(thresh,(255,255),iterations = 4 )
        thresh[:,2170:] = 0
        thresh[:,0:230] = 0
        thresh[0:val - 250,:] = 0
        thresh[val + 130:-1,:] = 0
        canny = cv2.Canny(thresh,200,255)
        
        

        #vertical = thresh
        # find the contours from the thresholded image
        _,contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        if np.count_nonzero(thresh[val,]) >= 500:
            #leftSide = np.nonzero(thresh[leftEdge,])[0][0]  - 39
            
            
        #print(lines)
            leftSide = np.nonzero(thresh[val,])[0][0]                     
            rightSide = np.nonzero(thresh[val,])[0][-1] 
            
            
            mmPpix = ((1/pixelsPerMetric)* (rightSide - leftSide)) 
            
            if mmPpix > 50:
                img  = cv2.line(img ,(leftSide ,alar[1]),(rightSide ,alar[3]),(255),4)


                img = cv2.circle(img,(leftSide,alar[1]) , 1, 0, 5)
                img = cv2.circle(img,(rightSide,alar[3]) , 1, 0, 5)

                font = cv2.FONT_HERSHEY_SIMPLEX
                img = cv2.putText(img,"{} mm".format(mmPpix),(0,330), font, 2 , (200,255,155), 2 , cv2.LINE_AA)

            
            
            '''verticalStructure = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 1520//50))
            # Apply morphology operations
            vertical = cv2.erode(thresh, verticalStructure)
            vertical = cv2.dilate(thresh, verticalStructure)
'''

        img1 = cv2.resize(img ,(int(1920),int(1080)))
        thresh1 = cv2.resize(thresh,(int(1920/2),int(1080/2)))
        canny1 = cv2.resize(canny,(int(1920/2),int(1080/2)))
        #cv2.cvtColor(img.copy(),cv2.COLOR_RGB2BGR)
        
        cv2.imshow('img ',img1)
        cv2.imshow(' thrsh ',thresh1)
        cv2.imshow('verticle',canny1)


       


        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    
    cap.release()
    cv2.destroyAllWindows()

      
if __name__== "__main__":
    main()

In [ ]:
2560/2

In [ ]:
abs(-5)

In [ ]:
[[644 859]]
[[643 864]]
[[644 875]]
[[642 865]]
[[643 872]]
[[642 871]]
[[642 875]]
[[644 858]]
[[644 858]]
[[644 858]]

In [ ]:
%matplotlib notebook

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import cv2

In [ ]:
cv2.HoughLinesP()

# with contours 

In [10]:
import cv2
import numpy as np
from scipy.spatial import distance as dist


cap = cv2.VideoCapture('C:/Users/shrin/Documents/Abhilash/tata steel/data from tata -14_v5/0 - 2020-02-13 16-51-30-240.mov')
#cap = cv2.VideoCapture('rtsp://admin:TATA_tsk123@10.152.235.180')

cap.set(cv2.CAP_PROP_POS_FRAMES,200)
alar = [420,1200 - 100  ,2041,1200 - 100  ]
#alar = [420,1000   ,2041,1200 -40   ]

leftEdge = 1200 +5 - 300 - 20 - 8

dB = dist.euclidean(alar[:2],alar[-2:])
pixelsPerMetric = dB / 1690

while(True):
    ret, img = cap.read()

    #img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    b,g,r = cv2.split(img.copy()) 

    yuv = cv2.cvtColor(img.copy(),cv2.COLOR_BGR2YUV)
    y,u,vb = cv2.split(yuv)

    randv = cv2.addWeighted(y, .5, b, 2., 0.0)  #good 220
    #randv = cv2.addWeighted(y, .5, r, 2.1, 0.0)


    dst = cv2.addWeighted(y, 0.005, randv, 1.3, 0.0)

    blur = cv2.GaussianBlur(dst,(3,3),0)

    _,thresh = cv2.threshold(blur,220,255,cv2.THRESH_BINARY )



    val = alar[1]
    thresh = cv2.erode(thresh,(255,255),iterations = 4 )
    thresh[:,2170:] = 0
    thresh[:,0:199] = 0
    thresh[0:val - 250,:] = 0
    thresh[val + 130:-1,:] = 0
    #vertical = thresh
    # find the contours from the thresholded image
    _,contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    # draw all contours
    contours = sorted(contours.copy(),key = cv2.contourArea, reverse=True)
    approx = cv2.approxPolyDP(contours[0], 0.0001* cv2.arcLength(contours[0], True), True)
    img = cv2.drawContours(img, [approx], 0, (0, 255, 0), 2)
    
    n = approx.ravel()
    #print(n)
    print(approx[0:][0:][1])



    #edges = cv.Canny(gray,50,150,apertureSize = 3)
    '''lines = cv2.HoughLinesP(thresh,1,np.pi/180,100,minLineLength=280,maxLineGap=10000)
    print(lines)
    for line in lines:
        x1,y1,x2,y2 = line[0]
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)'''



    #img  = cv2.line(img ,(alar[0] ,alar[1]),(alar[2] ,alar[3]),(255),5)
    #thresh  = cv2.line(thresh ,(alar[0] ,leftEdge),(alar[2] ,leftEdge),(255),2)
    #img  = cv2.line(img ,(alar[0] ,leftEdge),(alar[2] ,leftEdge),(255),5)
    point_left = list(np.squeeze(approx))
    val_x = list(np.squeeze(approx)[:,0:-1])
    val_y = list(np.squeeze(approx)[0:-1][:,1])
    #point_left(val_y.index(val))
    x,y,w,h = cv2.boundingRect(contours[0])
    try:
        #img = cv2.circle(img,(point_left[val_y.index(val)][0],point_left[val_y.index(val)][1]) , 1, 0, 25)
        img = cv2.circle(img,(x,y) , 1, 0, 15)
        img = cv2.circle(img,(x+w,y) , 1, 0, 15)
    
    except ValueError:
        print("")

    '''if np.count_nonzero(thresh[val,]) >= 500:
        #leftSide = np.nonzero(thresh[leftEdge,])[0][0]  - 39
        leftSide = np.nonzero(thresh[val,])[0][0]
        rightSide = np.nonzero(thresh[val,])[0][-1] 


        mmPpix = ((1/pixelsPerMetric)* (rightSide - leftSide)) 


        img  = cv2.line(img ,(leftSide ,alar[1]),(rightSide ,alar[3]),(255),4)


        img = cv2.circle(img,(leftSide,alar[1]) , 1, 0, 5)
        img = cv2.circle(img,(rightSide,alar[3]) , 1, 0, 5)

        font = cv2.FONT_HERSHEY_SIMPLEX
        img = cv2.putText(img,"{} mm".format(mmPpix),(0,330), font, 2 , (200,255,155), 2 , cv2.LINE_AA)



        verticalStructure = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 1520//50))
        # Apply morphology operations
        vertical = cv2.erode(thresh, verticalStructure)
        vertical = cv2.dilate(thresh, verticalStructure)'''


    img1 = cv2.resize(img ,(int(1920/2),int(1080/2)))
    thresh1 = cv2.resize(thresh,(int(1920/2),int(1080/2)))
    #vertical = cv2.resize(vertical,(int(1920/2),int(1080/2)))
    #cv2.cvtColor(img.copy(),cv2.COLOR_RGB2BGR)

    cv2.imshow('img ',img1)
    cv2.imshow(' thrsh ',thresh1)
    #cv2.imshow('verticle',vertical)





    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


cap.release()
cv2.destroyAllWindows()


[[644 859]]
[[643 864]]
[[644 875]]
[[642 865]]
[[643 872]]
[[642 871]]
[[642 875]]
[[644 858]]
[[644 858]]
[[644 858]]
[[644 858]]
[[642 864]]
[[642 875]]
[[643 861]]
[[642 871]]
[[642 867]]
[[642 869]]
[[643 862]]
[[643 865]]


In [11]:
import matplotlib.pyplot as plt
import imutils

In [23]:
cv2.imshow("rot",imutils.rotate(img1,.54))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
np.()

In [ ]:
point_left[val_y.index(val)]

In [ ]:
val_y.index(val)

In [ ]:
approx.argmin()

In [ ]:
approx[130]

In [ ]:
aaaa = np.squeeze(approx)

In [ ]:
val_x = list(np.squeeze(approx)[:,0:-1])

In [ ]:
val_y = list(np.squeeze(approx)[0:-1][:,1] )

In [ ]:
aaaa [0:-1][:,1] == val

In [ ]:
val_y.index(val)

In [ ]:
val_x[96]

In [ ]:
val_x

In [ ]:
aaaa[96]

In [ ]:
import cv2
import numpy as np

cap = cv2.VideoCapture('C:/Users/shrin/Documents/Abhilash/tata steel/data from tata -14_v5/0 - 2020-02-13 07-20-00-934.mov')
#cap = cv2.VideoCapture('rtsp://admin:TATA_tsk123@10.152.235.180')

cap.set(cv2.CAP_PROP_POS_FRAMES,200)
alar = [420,1200 - 100  ,2041,1200 - 100  ]

dB = dist.euclidean(alar[:2],alar[-2:])
pixelsPerMetric = dB / 1690


while(True):
    ret, img = cap.read()

    #img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    b,g,r = cv2.split(img.copy()) 

    yuv = cv2.cvtColor(img.copy(),cv2.COLOR_BGR2YUV)
    y,u,vb = cv2.split(yuv)

    randv = cv2.addWeighted(y, .5, b, 2., 0.0)  #good 220
    #randv = cv2.addWeighted(y, .5, r, 2.1, 0.0)


    dst = cv2.addWeighted(y, 0.005, randv, 1.3, 0.0)

    blur = cv2.GaussianBlur(dst,(3,3),0)

    _,thresh = cv2.threshold(blur,220,255,cv2.THRESH_BINARY )
    thresh = cv2.erode(thresh,(255,255),iterations = 4 )
    thresh[:,2170:] = 0
    thresh[:,0:199] = 0
    thresh[0:val - 100,:] = 0
    thresh[val + 100:-1,:] = 0
    
    _,contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    # draw all contours
    contours = sorted(contours.copy(),key = cv2.contourArea, reverse=True)
    approx = cv2.approxPolyDP(contours[0], 0.000000001* cv2.arcLength(contours[0], True), True)
    #img = cv2.drawContours(img, [approx], 0, (0, 255, 0), 2)
    
    x,y,w,h = cv2.boundingRect(approx)
    leftCnt = (x+25 , y + 150 )
    rightCnt = ( x+w -25 ,y + 150 )
    if np.count_nonzero(thresh[val,]) >= 500:
        img  = cv2.line(img ,leftCnt,rightCnt,(255),4)
        img = cv2.circle(img,leftCnt , 1, 0, 15)
        img = cv2.circle(img,rightCnt , 1, 0, 15)
        font = cv2.FONT_HERSHEY_SIMPLEX
        img = cv2.putText(img,"{} mm".format(w),(0,330), font, 2 , (200,255,155), 2 , cv2.LINE_AA)


    img1 = cv2.resize(img ,(int(1920/2),int(1080/2)))
    thresh1 = cv2.resize(thresh,(int(1920/2),int(1080/2)))
    
    cv2.imshow('img ',img1)
    cv2.imshow(' thrsh ',thresh1)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


cap.release()
cv2.destroyAllWindows()



### restrict corner

In [6]:
import cv2
import numpy as np
from scipy.spatial import distance as dist

cap = cv2.VideoCapture('C:/Users/shrin/Documents/Abhilash/tata steel/data from tata -14_v5/0 - 2020-02-13 07-20-00-934.mov')

In [7]:
cap.set(cv2.CAP_PROP_POS_FRAMES,50)
alar = [420,1200 - 100  ,2041,1200 - 100  ]

In [8]:
dB = dist.euclidean(alar[:2],alar[-2:])
pixelsPerMetric = dB / 1690
val = alar[1]
num = val + 95

In [9]:
while(True):
    ret, img = cap.read()

    #img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    b,g,r = cv2.split(img.copy()) 

    yuv = cv2.cvtColor(img.copy(),cv2.COLOR_BGR2YUV)
    y,u,vb = cv2.split(yuv)

    randv = cv2.addWeighted(y, .5, b, 2., 0.0)  #good 220
    #randv = cv2.addWeighted(y, .5, r, 2.1, 0.0)


    dst = cv2.addWeighted(y, 0.005, randv, 1.3, 0.0)

    blur = cv2.GaussianBlur(dst,(3,3),0)

    _,thresh = cv2.threshold(blur,220,255,cv2.THRESH_BINARY )
    thresh = cv2.erode(thresh,(255,255),iterations = 4 )
    thresh[:,2170:] = 0
    thresh[:,0:199] = 0
    thresh[0:val - 100,:] = 0
    thresh[val + 100:-1,:] = 0
    
    """------------------------------------------------start-end-----------------------------------------------------------"""
    if np.count_nonzero(thresh[val,]) >= 500:
        
        leftSide = np.nonzero(thresh[val,])[0][0]
        rightSide = np.nonzero(thresh[val,])[0][-1] 
        mmPpix = ((1/pixelsPerMetric)* (rightSide - leftSide))
        
        #num = val - 95
        img  = cv2.line(img ,(leftSide ,alar[1]),(rightSide ,alar[3]),(255),4)
        img = cv2.circle(img,(leftSide,alar[1]) , 1, 0, 5)
        img = cv2.circle(img,(rightSide,alar[3]) , 1, 0, 5)

        font = cv2.FONT_HERSHEY_SIMPLEX
        img = cv2.putText(img,"{} mm".format(mmPpix),(0,330), font, 2 , (200,255,155), 2 , cv2.LINE_AA)

    


    img1 = cv2.resize(img ,(int(1920/2),int(1080/2)))
    thresh1 = cv2.resize(thresh,(int(1920/2),int(1080/2)))
    
    cv2.imshow('img ',img1)
    cv2.imshow(' thrsh ',thresh1)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


cap.release()
cv2.destroyAllWindows()

